[package]
name = "calven"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
tokio = { version = "1.38.0", features = ["full"] }
serde = { version = "1.0.203", features = ["derive"] }

[dev-dependencies]
anyhow = "1.0.86"
cargo-watch = "8.5.2"
httpc-test = "0.1.9"
